package com.telekom.odsystem.organisms.cardwidget

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSCorners
import com.telekom.odsystem.foundations.ODSOffset
import com.telekom.odsystem.foundations.ODSPadding
import com.telekom.odsystem.foundations.SCALE_FACTOR

data class ODSCardWidgetTokens(
    val minHeight: Dp,
    val minWidth: Dp,
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignmentTypeBottomImage: Alignment.Horizontal,
    val horizontalAlignmentTypeTopImage: Alignment.Horizontal,
    val horizontalAlignmentTypeNoImage: Alignment.Horizontal,
    val verticalArrangement: Arrangement.Vertical,
    val cornerRadiusTypeNoImage: ODSCorners,
    val topImageContainerZStackContentAlignment: Alignment,
    val topImageContainerVerticalAlignment: Alignment.Vertical,
    val topImageContainerHorizontalAlignment: Alignment.Horizontal,
    val topImageContainerVerticalArrangement: Arrangement.Vertical,
    val topImageContainerContentAlignment: Alignment,
    val imageTopZStackClipContent: Boolean,
    val imageTopCornerRadius: ODSCorners,
    val imageTopVerticalAlignment: Alignment.Vertical,
    val imageTopHorizontalAlignment: Alignment.Horizontal,
    val imageTopVerticalArrangement: Arrangement.Vertical,
    val imageContentScale: ContentScale,
    val logoContainerAbsoluteOffsetTypeTopImage: ODSOffset,
    val logoContainerAbsoluteOffsetTypeTopImageStatePressed: ODSOffset,
    val logoContainerAbsoluteOffsetTypeBottomImage: ODSOffset,
    val logoContainerAbsoluteOffsetTypeBottomImageStatePressed: ODSOffset,
    val logoContainerAbsoluteOffsetTypeNoImage: ODSOffset,
    val logoContainerAbsoluteOffsetTypeTopImageStateHovered: ODSOffset,
    val logoContainerAbsoluteOffsetTypeBottomImageStateHovered: ODSOffset,
    val logoContainerAbsoluteContentAlignment: Alignment,
    val logoContainerCornerRadius: ODSCorners,
    val logoContainerHeight: Dp,
    val logoContainerWidth: Dp,
    val logoContainerVerticalAlignment: Alignment.Vertical,
    val logoContainerHorizontalAlignment: Alignment.Horizontal,
    val logoContainerVerticalArrangement: Arrangement.Vertical,
    val contentContainerZStackMinHeightTypeBottomImage: Dp,
    val contentContainerZStackMinHeightTypeTopImage: Dp,
    val contentContainerZStackMinHeightTypeNoImage: Dp,
    val contentContainerZStackContentAlignmentTypeBottomImage: Alignment,
    val contentContainerZStackContentAlignmentTypeTopImage: Alignment,
    val contentContainerZStackContentAlignmentTypeNoImage: Alignment,
    val contentContainerPaddingTypeBottomImage: ODSPadding,
    val contentContainerPaddingTypeTopImage: ODSPadding,
    val contentContainerPaddingTypeNoImage: ODSPadding,
    val contentContainerMinHeightTypeBottomImage: Dp,
    val contentContainerMinHeightTypeTopImage: Dp,
    val contentContainerMinHeightTypeNoImage: Dp,
    val contentContainerVerticalAlignment: Alignment.Vertical,
    val contentContainerHorizontalAlignmentTypeBottomImage: Alignment.Horizontal,
    val contentContainerHorizontalAlignmentTypeTopImage: Alignment.Horizontal,
    val contentContainerHorizontalAlignmentTypeNoImage: Alignment.Horizontal,
    val contentContainerVerticalArrangement: Arrangement.Vertical,
    val contentContainerContentAlignmentTypeBottomImage: Alignment,
    val contentContainerContentAlignmentTypeTopImage: Alignment,
    val contentContainerContentAlignmentTypeNoImage: Alignment,
    val contentContainerGapTypeNoImage: Dp,
    val backgroundCornerRadiusTypeBottomImage: ODSCorners,
    val backgroundCornerRadiusTypeTopImage: ODSCorners,
    val backgroundCornerRadiusTypeNoImage: ODSCorners,
    val backgroundVerticalAlignmentTypeNoImage: Alignment.Vertical,
    val backgroundHorizontalAlignmentTypeNoImage: Alignment.Horizontal,
    val backgroundVerticalArrangementTypeNoImage: Arrangement.Vertical,
    val bottomImageContainerZStackContentAlignment: Alignment,
    val bottomImageContainerVerticalAlignment: Alignment.Vertical,
    val bottomImageContainerHorizontalAlignment: Alignment.Horizontal,
    val bottomImageContainerVerticalArrangement: Arrangement.Vertical,
    val bottomImageContainerContentAlignment: Alignment,
    val imageBottomZStackClipContent: Boolean,
    val imageBottomCornerRadius: ODSCorners,
    val imageBottomVerticalAlignment: Alignment.Vertical,
    val imageBottomHorizontalAlignment: Alignment.Horizontal,
    val imageBottomVerticalArrangement: Arrangement.Vertical,
    val image2ContentScale: ContentScale,
    val logoContainer2AbsoluteOffsetTypeTopImage: ODSOffset,
    val logoContainer2AbsoluteOffsetTypeNoImage: ODSOffset,
    val logoContainer2AbsoluteOffsetTypeBottomImage: ODSOffset,
    val logoContainer2AbsoluteOffsetTypeBottomImageStatePressed: ODSOffset,
    val logoContainer2AbsoluteOffsetTypeBottomImageStateHovered: ODSOffset,
    val logoContainer2AbsoluteContentAlignment: Alignment,
    val logoContainer2CornerRadius: ODSCorners,
    val logoContainer2Width: Dp,
    val logoContainer2Height: Dp,
    val logoContainer2VerticalAlignment: Alignment.Vertical,
    val logoContainer2HorizontalAlignment: Alignment.Horizontal,
    val logoContainer2VerticalArrangement: Arrangement.Vertical,
    var scaleFactor: Float? = null, // Not exported from the plugin
    var verticalImageOffset: Dp? = null, // Not exported from the plugin
    var imageTopHeight: Dp? = null, // Not exported from the plugin
    var imageBottomHeight: Dp? = null, // Not exported from the plugin
)

val defaultODSCardWidgetTokens = ODSCardWidgetTokens(
    minHeight = 154.dp,
    minWidth = 154.dp,
    verticalAlignment = Alignment.Top,
    horizontalAlignmentTypeBottomImage = Alignment.CenterHorizontally,
    horizontalAlignmentTypeTopImage = Alignment.CenterHorizontally,
    horizontalAlignmentTypeNoImage = Alignment.Start,
    verticalArrangement = Arrangement.Top,
    cornerRadiusTypeNoImage = ODSCorners(all = DSVariables.radiusMedium),
    topImageContainerZStackContentAlignment = Alignment.Center,
    topImageContainerVerticalAlignment = Alignment.CenterVertically,
    topImageContainerHorizontalAlignment = Alignment.CenterHorizontally,
    topImageContainerVerticalArrangement = Arrangement.Center,
    topImageContainerContentAlignment = Alignment.Center,
    imageTopZStackClipContent = true,
    imageTopCornerRadius = ODSCorners(
        topLeft = DSVariables.radiusMedium,
        topRight = DSVariables.radiusMedium,
        bottomLeft = 0.dp,
        bottomRight = 0.dp
    ),
    imageTopVerticalAlignment = Alignment.Top,
    imageTopHorizontalAlignment = Alignment.Start,
    imageTopVerticalArrangement = Arrangement.Top,
    imageContentScale = ContentScale.Crop,
    logoContainerAbsoluteOffsetTypeTopImage = ODSOffset(x = -16.dp, y = 16.dp),
    logoContainerAbsoluteOffsetTypeTopImageStatePressed = ODSOffset(x = -16.dp, y = 16.dp),
    logoContainerAbsoluteOffsetTypeBottomImage = ODSOffset(x = -16.dp, y = 16.dp),
    logoContainerAbsoluteOffsetTypeBottomImageStatePressed = ODSOffset(x = -16.dp, y = 16.dp),
    logoContainerAbsoluteOffsetTypeNoImage = ODSOffset(x = -20.dp, y = 19.dp),
    logoContainerAbsoluteOffsetTypeTopImageStateHovered = ODSOffset(x = -20.dp, y = 19.dp),
    logoContainerAbsoluteOffsetTypeBottomImageStateHovered = ODSOffset(x = -20.dp, y = 19.dp),
    logoContainerAbsoluteContentAlignment = Alignment.TopEnd,
    logoContainerCornerRadius = ODSCorners(all = DSVariables.radiusFull),
    logoContainerHeight = DSVariables.sizingComponent12,
    logoContainerWidth = DSVariables.sizingComponent12,
    logoContainerVerticalAlignment = Alignment.Top,
    logoContainerHorizontalAlignment = Alignment.Start,
    logoContainerVerticalArrangement = Arrangement.Top,
    contentContainerZStackMinHeightTypeBottomImage = DSVariables.sizingComponent15,
    contentContainerZStackMinHeightTypeTopImage = DSVariables.sizingComponent15,
    contentContainerZStackMinHeightTypeNoImage = 154.dp,
    contentContainerZStackContentAlignmentTypeBottomImage = Alignment.TopCenter,
    contentContainerZStackContentAlignmentTypeTopImage = Alignment.TopCenter,
    contentContainerZStackContentAlignmentTypeNoImage = Alignment.TopStart,
    contentContainerPaddingTypeBottomImage = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent3,
        left = DSVariables.spacingComponent5,
        right = DSVariables.spacingComponent5
    ),
    contentContainerPaddingTypeTopImage = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent3,
        left = DSVariables.spacingComponent5,
        right = DSVariables.spacingComponent5
    ),
    contentContainerPaddingTypeNoImage = ODSPadding(all = DSVariables.spacingComponent5),
    contentContainerMinHeightTypeBottomImage = DSVariables.sizingComponent15,
    contentContainerMinHeightTypeTopImage = DSVariables.sizingComponent15,
    contentContainerMinHeightTypeNoImage = 154.dp,
    contentContainerVerticalAlignment = Alignment.Top,
    contentContainerHorizontalAlignmentTypeBottomImage = Alignment.CenterHorizontally,
    contentContainerHorizontalAlignmentTypeTopImage = Alignment.CenterHorizontally,
    contentContainerHorizontalAlignmentTypeNoImage = Alignment.Start,
    contentContainerVerticalArrangement = Arrangement.Top,
    contentContainerContentAlignmentTypeBottomImage = Alignment.TopCenter,
    contentContainerContentAlignmentTypeTopImage = Alignment.TopCenter,
    contentContainerContentAlignmentTypeNoImage = Alignment.TopStart,
    contentContainerGapTypeNoImage = DSVariables.spacingComponent3,
    backgroundCornerRadiusTypeBottomImage = ODSCorners(
        topLeft = DSVariables.radiusMedium,
        topRight = DSVariables.radiusMedium,
        bottomLeft = 0.dp,
        bottomRight = 0.dp
    ),
    backgroundCornerRadiusTypeTopImage = ODSCorners(
        topLeft = 0.dp,
        topRight = 0.dp,
        bottomLeft = DSVariables.radiusMedium,
        bottomRight = DSVariables.radiusMedium
    ),
    backgroundCornerRadiusTypeNoImage = ODSCorners(all = DSVariables.radiusMedium),
    backgroundVerticalAlignmentTypeNoImage = Alignment.Top,
    backgroundHorizontalAlignmentTypeNoImage = Alignment.Start,
    backgroundVerticalArrangementTypeNoImage = Arrangement.Top,
    bottomImageContainerZStackContentAlignment = Alignment.Center,
    bottomImageContainerVerticalAlignment = Alignment.CenterVertically,
    bottomImageContainerHorizontalAlignment = Alignment.CenterHorizontally,
    bottomImageContainerVerticalArrangement = Arrangement.Center,
    bottomImageContainerContentAlignment = Alignment.Center,
    imageBottomZStackClipContent = true,
    imageBottomCornerRadius = ODSCorners(
        topLeft = 0.dp,
        topRight = 0.dp,
        bottomLeft = DSVariables.radiusMedium,
        bottomRight = DSVariables.radiusMedium
    ),
    imageBottomVerticalAlignment = Alignment.Top,
    imageBottomHorizontalAlignment = Alignment.Start,
    imageBottomVerticalArrangement = Arrangement.Top,
    image2ContentScale = ContentScale.Crop,
    logoContainer2AbsoluteOffsetTypeTopImage = ODSOffset(x = 16.dp, y = -16.dp),
    logoContainer2AbsoluteOffsetTypeNoImage = ODSOffset(x = 16.dp, y = -16.dp),
    logoContainer2AbsoluteOffsetTypeBottomImage = ODSOffset(x = 16.dp, y = -16.dp),
    logoContainer2AbsoluteOffsetTypeBottomImageStatePressed = ODSOffset(x = 16.dp, y = -16.dp),
    logoContainer2AbsoluteOffsetTypeBottomImageStateHovered = ODSOffset(x = 20.dp, y = -20.dp),
    logoContainer2AbsoluteContentAlignment = Alignment.BottomStart,
    logoContainer2CornerRadius = ODSCorners(all = DSVariables.radiusFull),
    logoContainer2Width = DSVariables.sizingComponent12,
    logoContainer2Height = DSVariables.sizingComponent12,
    logoContainer2VerticalAlignment = Alignment.Top,
    logoContainer2HorizontalAlignment = Alignment.Start,
    logoContainer2VerticalArrangement = Arrangement.Top,
    scaleFactor = SCALE_FACTOR,
    verticalImageOffset = 8.dp,
    imageTopHeight = 90.dp,
    imageBottomHeight = 90.dp,
)

var DSCardWidgetTokens: ODSCardWidgetTokens = defaultODSCardWidgetTokens
