package com.telekom.odsystem.atoms.sparkline

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSCorners
import com.telekom.odsystem.foundations.ODSPadding

data class ODSSparklineTokens(
    var gapTypeBars: Dp,
    var verticalAlignmentTypeBars: Alignment.Vertical,
    var verticalAlignmentTypeProgressBar: Alignment.Vertical,
    var horizontalAlignment: Alignment.Horizontal,
    var horizontalArrangementTypeBars: Arrangement.Horizontal,
    var borderRadiusTypeProgressBar: ODSCorners,
    var minWidthTypeProgressBarSizeSmall: Dp,
    var minWidthTypeProgressBarSizeLarge: Dp,
    var widthTypeProgressBarSizeSmall: Dp,
    var widthTypeProgressBarSizeLarge: Dp,
    var heightTypeProgressBar: Dp,
    var clipContentTypeProgressBar: Boolean,
    var verticalArrangementTypeProgressBar: Arrangement.Vertical,
    var bar1BorderRadiusTypeBars: ODSCorners,
    var bar1WidthTypeBarsSizeSmall: Dp,
    var bar1WidthTypeBarsSizeLarge: Dp,
    var bar1HeightTypeBarsSizeSmall: Dp,
    var bar1HeightTypeBarsSizeLarge: Dp,
    var bar1ClipContentTypeBars: Boolean,
    var bar1VerticalAlignmentTypeBars: Alignment.Vertical,
    var bar1HorizontalAlignmentTypeBarsSizeSmall: Alignment.Horizontal,
    var bar1HorizontalAlignmentTypeBarsSizeLarge: Alignment.Horizontal,
    var bar1HorizontalArrangementTypeBarsSizeSmall: Arrangement.Horizontal,
    var bar1PaddingTypeBarsSizeLarge: ODSPadding,
    var bar1VerticalArrangementTypeBarsSizeLarge: Arrangement.Vertical,
    var dotIndicatorBorderRadius: ODSCorners,
    var dotIndicatorWidth: Dp,
    var dotIndicatorHeight: Dp,
    var dotIndicatorClipContent: Boolean,
    var bar2BorderRadiusTypeBars: ODSCorners,
    var bar2WidthTypeBarsSizeSmall: Dp,
    var bar2WidthTypeBarsSizeLarge: Dp,
    var bar2HeightTypeBarsSizeSmall: Dp,
    var bar2HeightTypeBarsSizeLarge: Dp,
    var bar2ClipContentTypeBars: Boolean,
    var bar3BorderRadiusTypeBars: ODSCorners,
    var bar3WidthTypeBarsSizeSmall: Dp,
    var bar3WidthTypeBarsSizeLarge: Dp,
    var bar3HeightTypeBarsSizeSmall: Dp,
    var bar3HeightTypeBarsSizeLarge: Dp,
    var bar3ClipContentTypeBars: Boolean,
    var bar4BorderRadiusTypeBars: ODSCorners,
    var bar4WidthTypeBarsSizeSmall: Dp,
    var bar4WidthTypeBarsSizeLarge: Dp,
    var bar4HeightTypeBarsSizeSmall: Dp,
    var bar4HeightTypeBarsSizeLarge: Dp,
    var bar4ClipContentTypeBars: Boolean,
    var bar5BorderRadiusTypeBars: ODSCorners,
    var bar5WidthTypeBarsSizeSmall: Dp,
    var bar5WidthTypeBarsSizeLarge: Dp,
    var bar5HeightTypeBarsSizeSmall: Dp,
    var bar5HeightTypeBarsSizeLarge: Dp,
    var bar5ClipContentTypeBars: Boolean,
    var bar6BorderRadiusTypeBars: ODSCorners,
    var bar6WidthTypeBarsSizeSmall: Dp,
    var bar6WidthTypeBarsSizeLarge: Dp,
    var bar6HeightTypeBarsSizeSmall: Dp,
    var bar6HeightTypeBarsSizeLarge: Dp,
    var bar6ClipContentTypeBars: Boolean,
    var bar7BorderRadiusTypeBars: ODSCorners,
    var bar7WidthTypeBarsSizeSmall: Dp,
    var bar7WidthTypeBarsSizeLarge: Dp,
    var bar7HeightTypeBarsSizeSmall: Dp,
    var bar7HeightTypeBarsSizeLarge: Dp,
    var bar7ClipContentTypeBars: Boolean,
    var bar8BorderRadiusTypeBars: ODSCorners,
    var bar8WidthTypeBarsSizeSmall: Dp,
    var bar8WidthTypeBarsSizeLarge: Dp,
    var bar8HeightTypeBarsSizeSmall: Dp,
    var bar8HeightTypeBarsSizeLarge: Dp,
    var bar8ClipContentTypeBars: Boolean,
    var bar8VerticalAlignmentTypeBars: Alignment.Vertical,
    var bar8HorizontalAlignmentTypeBarsSizeSmall: Alignment.Horizontal,
    var bar8HorizontalAlignmentTypeBarsSizeLarge: Alignment.Horizontal,
    var bar8HorizontalArrangementTypeBarsSizeSmall: Arrangement.Horizontal,
    var bar8PaddingTypeBarsSizeLarge: ODSPadding,
    var bar8VerticalArrangementTypeBarsSizeLarge: Arrangement.Vertical,
//    var progressIndicatorWidthTypeProgressBarPercentage0SizeSmall: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage25SizeSmall: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage50SizeSmall: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage75SizeSmall: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage100SizeSmall: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage0SizeLarge: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage25SizeLarge: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage50SizeLarge: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage75SizeLarge: Dp,
//    var progressIndicatorWidthTypeProgressBarPercentage100SizeLarge: Dp,
    var progressIndicatorHeightTypeProgressBar: Dp,
    var dotIndicator1BorderRadiusTypeProgressBar: ODSCorners,
    var dotIndicator1WidthTypeProgressBar: Dp,
    var dotIndicator1HeightTypeProgressBar: Dp,
    var dotIndicator1ClipContentTypeProgressBar: Boolean,

    // Custom Addition
    var barWidthSmall: Dp,
    var barWidthLarge: Dp,
    var dotHorizontalPadding: ODSPadding,
    var dotHorizontalArrangement: Arrangement.Horizontal,
)

var defaultODSSparklineTokens = ODSSparklineTokens(
    gapTypeBars = DSVariables.spacingComponent1,
    verticalAlignmentTypeBars = Alignment.Bottom,
    verticalAlignmentTypeProgressBar = Alignment.CenterVertically,
    horizontalAlignment = Alignment.CenterHorizontally,
    horizontalArrangementTypeBars = Arrangement.Center,
    borderRadiusTypeProgressBar = ODSCorners(all = DSVariables.radiusMedium),
    minWidthTypeProgressBarSizeSmall = 56.dp,
    minWidthTypeProgressBarSizeLarge = 120.dp,
    widthTypeProgressBarSizeSmall = 56.dp,
    widthTypeProgressBarSizeLarge = 120.dp,
    heightTypeProgressBar = DSVariables.sizingComponent4,
    clipContentTypeProgressBar = true,
    verticalArrangementTypeProgressBar = Arrangement.Center,
    bar1BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar1WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar1WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar1HeightTypeBarsSizeSmall = DSVariables.sizingComponent6,
    bar1HeightTypeBarsSizeLarge = DSVariables.sizingComponent10,
    bar1ClipContentTypeBars = true,
    bar1VerticalAlignmentTypeBars = Alignment.Bottom,
    bar1HorizontalAlignmentTypeBarsSizeSmall = Alignment.Start,
    bar1HorizontalAlignmentTypeBarsSizeLarge = Alignment.CenterHorizontally,
    bar1HorizontalArrangementTypeBarsSizeSmall = Arrangement.Start,
    bar1PaddingTypeBarsSizeLarge = ODSPadding(all = DSVariables.spacingComponent1),
    bar1VerticalArrangementTypeBarsSizeLarge = Arrangement.Bottom,
    dotIndicatorBorderRadius = ODSCorners(all = DSVariables.radiusFull),
    dotIndicatorWidth = 4.dp,
    dotIndicatorHeight = 4.dp,
    dotIndicatorClipContent = true,
    bar2BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar2WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar2WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar2HeightTypeBarsSizeSmall = DSVariables.sizingComponent7,
    bar2HeightTypeBarsSizeLarge = DSVariables.sizingComponent12,
    bar2ClipContentTypeBars = true,
    bar3BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar3WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar3WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar3HeightTypeBarsSizeSmall = DSVariables.sizingComponent6,
    bar3HeightTypeBarsSizeLarge = DSVariables.sizingComponent10,
    bar3ClipContentTypeBars = true,
    bar4BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar4WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar4WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar4HeightTypeBarsSizeSmall = DSVariables.sizingComponent5,
    bar4HeightTypeBarsSizeLarge = DSVariables.sizingComponent8,
    bar4ClipContentTypeBars = true,
    bar5BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar5WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar5WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar5HeightTypeBarsSizeSmall = DSVariables.sizingComponent4,
    bar5HeightTypeBarsSizeLarge = DSVariables.sizingComponent7,
    bar5ClipContentTypeBars = true,
    bar6BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar6WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar6WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar6HeightTypeBarsSizeSmall = DSVariables.sizingComponent6,
    bar6HeightTypeBarsSizeLarge = DSVariables.sizingComponent10,
    bar6ClipContentTypeBars = true,
    bar7BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar7WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar7WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar7HeightTypeBarsSizeSmall = DSVariables.sizingComponent7,
    bar7HeightTypeBarsSizeLarge = DSVariables.sizingComponent12,
    bar7ClipContentTypeBars = true,
    bar8BorderRadiusTypeBars = ODSCorners(all = DSVariables.radiusFull),
    bar8WidthTypeBarsSizeSmall = DSVariables.sizingComponent3,
    bar8WidthTypeBarsSizeLarge = DSVariables.sizingComponent4,
    bar8HeightTypeBarsSizeSmall = DSVariables.sizingComponent5,
    bar8HeightTypeBarsSizeLarge = DSVariables.sizingComponent8,
    bar8ClipContentTypeBars = true,
    bar8VerticalAlignmentTypeBars = Alignment.Bottom,
    bar8HorizontalAlignmentTypeBarsSizeSmall = Alignment.Start,
    bar8HorizontalAlignmentTypeBarsSizeLarge = Alignment.CenterHorizontally,
    bar8HorizontalArrangementTypeBarsSizeSmall = Arrangement.Start,
    bar8PaddingTypeBarsSizeLarge = ODSPadding(all = DSVariables.spacingComponent1),
    bar8VerticalArrangementTypeBarsSizeLarge = Arrangement.Bottom,
//    progressIndicatorWidthTypeProgressBarPercentage0SizeSmall = 1.dp,
//    progressIndicatorWidthTypeProgressBarPercentage25SizeSmall = 20.dp,
//    progressIndicatorWidthTypeProgressBarPercentage50SizeSmall = 28.dp,
//    progressIndicatorWidthTypeProgressBarPercentage75SizeSmall = 42.dp,
//    progressIndicatorWidthTypeProgressBarPercentage100SizeSmall = 56.dp,
//    progressIndicatorWidthTypeProgressBarPercentage0SizeLarge = 2.dp,
//    progressIndicatorWidthTypeProgressBarPercentage25SizeLarge = 30.dp,
//    progressIndicatorWidthTypeProgressBarPercentage50SizeLarge = 60.dp,
//    progressIndicatorWidthTypeProgressBarPercentage75SizeLarge = 90.dp,
//    progressIndicatorWidthTypeProgressBarPercentage100SizeLarge = 120.dp,
    progressIndicatorHeightTypeProgressBar = 8.dp,
    dotIndicator1BorderRadiusTypeProgressBar = ODSCorners(all = DSVariables.radiusFull),
    dotIndicator1WidthTypeProgressBar = 4.dp,
    dotIndicator1HeightTypeProgressBar = 4.dp,
    dotIndicator1ClipContentTypeProgressBar = true,
    barWidthSmall = DSVariables.sizingComponent3,
    barWidthLarge = 8.dp,
    dotHorizontalPadding = ODSPadding(horizontal = DSVariables.spacingComponent1),
    dotHorizontalArrangement = Arrangement.SpaceBetween
)

var DSSparklineTokens: ODSSparklineTokens = defaultODSSparklineTokens
