package com.telekom.odsystem.componenttokens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSTextStyles
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSCorners
import com.telekom.odsystem.foundations.ODSPadding
import com.telekom.odsystem.foundations.ODSTextStyle
import com.telekom.odsystem.foundations.SCALE_FACTOR

data class ODSButtonTokens(
    val paddingButtonTypeStandardSizeLarge: ODSPadding,
    val paddingButtonTypeStandardVariantGhostSizeLarge: ODSPadding,
    val paddingButtonTypeIconOnlySizeLarge: ODSPadding,
    val paddingButtonTypeStandardSizeSmall: ODSPadding,
    val paddingButtonTypeStandardVariantGhostSizeSmall: ODSPadding,
    val paddingButtonTypeIconOnlySizeSmall: ODSPadding,
    val borderRadius: ODSCorners,
    val minHeightSizeLarge: Dp,
    val minHeightSizeSmall: Dp,
    val minWidthButtonTypeStandardSizeLarge: Dp,
    val minWidthButtonTypeIconOnlySizeLarge: Dp,
    val minWidthButtonTypeStandardSizeSmall: Dp,
    val minWidthButtonTypeIconOnlySizeSmall: Dp,
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignment: Alignment.Horizontal,
    val horizontalArrangement: Arrangement.Horizontal,
    val contentAlignment: Alignment,
    val maxHeightButtonTypeIconOnlySizeLarge: Dp,
    val maxHeightButtonTypeIconOnlySizeSmall: Dp,
    val maxWidthButtonTypeIconOnlySizeLarge: Dp,
    val maxWidthButtonTypeIconOnlySizeSmall: Dp,
    val buttonBgBorderRadius: ODSCorners,
    val buttonBgHeightVariantGhostSizeLarge: Dp,
    val buttonBgHeightVariantOutlineSizeLargeDisabled: Dp,
    val buttonBgHeightVariantOutlineSizeLarge: Dp,
    val buttonBgHeightVariantOutlineSizeLargeStatePressed: Dp,
    val buttonBgHeightVariantSecondarySizeLargeDisabled: Dp,
    val buttonBgHeightVariantSecondarySizeLarge: Dp,
    val buttonBgHeightVariantSecondarySizeLargeStatePressed: Dp,
    val buttonBgHeightVariantPrimarySizeLargeDisabled: Dp,
    val buttonBgHeightVariantPrimarySizeLarge: Dp,
    val buttonBgHeightVariantPrimarySizeLargeStatePressed: Dp,
    val buttonBgHeightVariantOutlineSizeLargeStateHovered: Dp,
    val buttonBgHeightVariantPrimarySizeLargeStateHovered: Dp,
    val buttonBgHeightVariantSecondarySizeLargeStateHovered: Dp,
    val buttonBgHeightVariantGhostSizeSmall: Dp,
    val buttonBgHeightVariantOutlineSizeSmallDisabled: Dp,
    val buttonBgHeightVariantOutlineSizeSmall: Dp,
    val buttonBgHeightVariantOutlineSizeSmallStatePressed: Dp,
    val buttonBgHeightVariantSecondarySizeSmallDisabled: Dp,
    val buttonBgHeightVariantSecondarySizeSmall: Dp,
    val buttonBgHeightVariantSecondarySizeSmallStatePressed: Dp,
    val buttonBgHeightVariantPrimarySizeSmallDisabled: Dp,
    val buttonBgHeightVariantPrimarySizeSmall: Dp,
    val buttonBgHeightVariantPrimarySizeSmallStatePressed: Dp,
    val buttonBgHeightVariantOutlineSizeSmallStateHovered: Dp,
    val buttonBgHeightVariantSecondarySizeSmallStateHovered: Dp,
    val buttonBgHeightVariantPrimarySizeSmallStateHovered: Dp,
    val buttonBgContentAlignmentButtonTypeStandard: Alignment,
    val buttonBgContentAlignmentButtonTypeIconOnly: Alignment,
    val buttonBgBorderVariantOutline: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantGhostSizeLarge: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLarge: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLarge: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLarge: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeStateHovered: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeStateHovered: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeStateHovered: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantGhostSizeSmall: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmall: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmall: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallDisabled: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmall: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallStatePressed: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallStateHovered: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallStateHovered: Dp,
    val buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallStateHovered: Dp,
    val contentGapSizeLarge: Dp,
    val contentGapSizeSmall: Dp,
    val contentPaddingButtonTypeIconOnly: ODSPadding,
    val contentPaddingButtonTypeStandardSizeLarge: ODSPadding,
    val contentPaddingButtonTypeStandardSizeSmall: ODSPadding,
    val contentVerticalAlignment: Alignment.Vertical,
    val contentHorizontalAlignment: Alignment.Horizontal,
    val contentHorizontalArrangement: Arrangement.Horizontal,
    val leftIconVerticalAlignmentButtonTypeStandard: Alignment.Vertical,
    val leftIconHorizontalAlignmentButtonTypeStandard: Alignment.Horizontal,
    val leftIconHorizontalArrangementButtonTypeStandard: Arrangement.Horizontal,
    val buttonIconWidthButtonTypeStandardSizeLarge: Dp,
    val buttonIconWidthButtonTypeStandardSizeSmall: Dp,
    val buttonIconHeightButtonTypeStandardSizeLarge: Dp,
    val buttonIconHeightButtonTypeStandardSizeSmall: Dp,
    val buttonLabelTextStyleButtonTypeStandardSizeLarge: ODSTextStyle,
    val buttonLabelTextStyleButtonTypeStandardSizeSmall: ODSTextStyle,
    val buttonLabelTextAlignButtonTypeStandard: TextAlign,
    val rightIconVerticalAlignmentButtonTypeStandard: Alignment.Vertical,
    val rightIconHorizontalAlignmentButtonTypeStandard: Alignment.Horizontal,
    val rightIconHorizontalArrangementButtonTypeStandard: Arrangement.Horizontal,
    val buttonIcon2WidthButtonTypeStandardSizeLarge: Dp,
    val buttonIcon2WidthButtonTypeStandardSizeSmall: Dp,
    val buttonIcon2HeightButtonTypeStandardSizeLarge: Dp,
    val buttonIcon2HeightButtonTypeStandardSizeSmall: Dp,
    val buttonIcon3WidthButtonTypeIconOnlySizeLarge: Dp,
    val buttonIcon3WidthButtonTypeIconOnlySizeSmall: Dp,
    val buttonIcon3HeightButtonTypeIconOnlySizeLarge: Dp,
    val buttonIcon3HeightButtonTypeIconOnlySizeSmall: Dp,
    val scaleFactor: Float, // Not exported from plugin
    var buttonLabelTextOverflow: TextOverflow? // Not exported from the plugin
)

val defaultODSButtonTokens = ODSButtonTokens(
    paddingButtonTypeStandardSizeLarge = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2,
        left = DSVariables.spacingComponent8,
        right = DSVariables.spacingComponent8
    ),
    paddingButtonTypeStandardVariantGhostSizeLarge = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent7
    ),
    paddingButtonTypeIconOnlySizeLarge = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent6,
        right = DSVariables.spacingComponent6
    ),
    paddingButtonTypeStandardSizeSmall = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2,
        left = DSVariables.spacingComponent6,
        right = DSVariables.spacingComponent6
    ),
    paddingButtonTypeStandardVariantGhostSizeSmall = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2,
        left = DSVariables.spacingComponent5,
        right = DSVariables.spacingComponent5
    ),
    paddingButtonTypeIconOnlySizeSmall = ODSPadding(
        top = DSVariables.spacingComponent4,
        bottom = DSVariables.spacingComponent4,
        left = DSVariables.spacingComponent5,
        right = DSVariables.spacingComponent5
    ),
    borderRadius = ODSCorners(all = DSVariables.radiusFull),
    minHeightSizeLarge = DSVariables.sizingComponent15,
    minHeightSizeSmall = DSVariables.sizingComponent14,
    minWidthButtonTypeStandardSizeLarge = DSVariables.sizingComponent20,
    minWidthButtonTypeIconOnlySizeLarge = DSVariables.sizingComponent15,
    minWidthButtonTypeStandardSizeSmall = DSVariables.sizingComponent18,
    minWidthButtonTypeIconOnlySizeSmall = DSVariables.sizingComponent14,
    verticalAlignment = Alignment.CenterVertically,
    horizontalAlignment = Alignment.CenterHorizontally,
    horizontalArrangement = Arrangement.Center,
    contentAlignment = Alignment.Center,
    maxHeightButtonTypeIconOnlySizeLarge = DSVariables.sizingComponent15,
    maxHeightButtonTypeIconOnlySizeSmall = DSVariables.sizingComponent14,
    maxWidthButtonTypeIconOnlySizeLarge = DSVariables.sizingComponent15,
    maxWidthButtonTypeIconOnlySizeSmall = DSVariables.sizingComponent14,
    buttonBgBorderRadius = ODSCorners(all = DSVariables.radiusFull),
    buttonBgHeightVariantGhostSizeLarge = 64.dp,
    buttonBgHeightVariantOutlineSizeLargeDisabled = 64.dp,
    buttonBgHeightVariantOutlineSizeLarge = 64.dp,
    buttonBgHeightVariantOutlineSizeLargeStatePressed = 64.dp,
    buttonBgHeightVariantSecondarySizeLargeDisabled = 64.dp,
    buttonBgHeightVariantSecondarySizeLarge = 64.dp,
    buttonBgHeightVariantSecondarySizeLargeStatePressed = 64.dp,
    buttonBgHeightVariantPrimarySizeLargeDisabled = 64.dp,
    buttonBgHeightVariantPrimarySizeLarge = 64.dp,
    buttonBgHeightVariantPrimarySizeLargeStatePressed = 64.dp,
    buttonBgHeightVariantOutlineSizeLargeStateHovered = 68.dp,
    buttonBgHeightVariantPrimarySizeLargeStateHovered = 68.dp,
    buttonBgHeightVariantSecondarySizeLargeStateHovered = 68.dp,
    buttonBgHeightVariantGhostSizeSmall = 40.dp,
    buttonBgHeightVariantOutlineSizeSmallDisabled = 40.dp,
    buttonBgHeightVariantOutlineSizeSmall = 40.dp,
    buttonBgHeightVariantOutlineSizeSmallStatePressed = 40.dp,
    buttonBgHeightVariantSecondarySizeSmallDisabled = 40.dp,
    buttonBgHeightVariantSecondarySizeSmall = 40.dp,
    buttonBgHeightVariantSecondarySizeSmallStatePressed = 40.dp,
    buttonBgHeightVariantPrimarySizeSmallDisabled = 40.dp,
    buttonBgHeightVariantPrimarySizeSmall = 40.dp,
    buttonBgHeightVariantPrimarySizeSmallStatePressed = 40.dp,
    buttonBgHeightVariantOutlineSizeSmallStateHovered = 44.dp,
    buttonBgHeightVariantSecondarySizeSmallStateHovered = 44.dp,
    buttonBgHeightVariantPrimarySizeSmallStateHovered = 44.dp,
    buttonBgContentAlignmentButtonTypeStandard = Alignment.CenterStart,
    buttonBgContentAlignmentButtonTypeIconOnly = Alignment.Center,
    buttonBgBorderVariantOutline = DSVariables.strokes1,
    buttonBgWidthButtonTypeIconOnlyVariantGhostSizeLarge = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeDisabled = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLarge = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeStatePressed = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeDisabled = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLarge = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeStatePressed = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeDisabled = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLarge = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeStatePressed = 64.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeLargeStateHovered = 68.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeLargeStateHovered = 68.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeLargeStateHovered = 68.dp,
    buttonBgWidthButtonTypeIconOnlyVariantGhostSizeSmall = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallDisabled = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmall = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallStatePressed = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallDisabled = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmall = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallStatePressed = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallDisabled = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmall = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallStatePressed = 40.dp,
    buttonBgWidthButtonTypeIconOnlyVariantOutlineSizeSmallStateHovered = 44.dp,
    buttonBgWidthButtonTypeIconOnlyVariantSecondarySizeSmallStateHovered = 44.dp,
    buttonBgWidthButtonTypeIconOnlyVariantPrimarySizeSmallStateHovered = 44.dp,
    contentGapSizeLarge = DSVariables.spacingComponent5,
    contentGapSizeSmall = DSVariables.spacingComponent3,
    contentPaddingButtonTypeIconOnly = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2
    ),
    contentPaddingButtonTypeStandardSizeLarge = ODSPadding(
        top = DSVariables.spacingComponent2,
        bottom = DSVariables.spacingComponent2
    ),
    contentPaddingButtonTypeStandardSizeSmall = ODSPadding(
        top = DSVariables.spacingComponent1,
        bottom = DSVariables.spacingComponent1
    ),
    contentVerticalAlignment = Alignment.CenterVertically,
    contentHorizontalAlignment = Alignment.CenterHorizontally,
    contentHorizontalArrangement = Arrangement.Center,
    leftIconVerticalAlignmentButtonTypeStandard = Alignment.CenterVertically,
    leftIconHorizontalAlignmentButtonTypeStandard = Alignment.CenterHorizontally,
    leftIconHorizontalArrangementButtonTypeStandard = Arrangement.Center,
    buttonIconWidthButtonTypeStandardSizeLarge = DSVariables.sizingComponent10,
    buttonIconWidthButtonTypeStandardSizeSmall = DSVariables.sizingComponent7,
    buttonIconHeightButtonTypeStandardSizeLarge = DSVariables.sizingComponent10,
    buttonIconHeightButtonTypeStandardSizeSmall = DSVariables.sizingComponent7,
    buttonLabelTextStyleButtonTypeStandardSizeLarge = DSTextStyles.bodyL,
    buttonLabelTextStyleButtonTypeStandardSizeSmall = DSTextStyles.bodyMBold,
    buttonLabelTextAlignButtonTypeStandard = TextAlign.Center,
    rightIconVerticalAlignmentButtonTypeStandard = Alignment.CenterVertically,
    rightIconHorizontalAlignmentButtonTypeStandard = Alignment.CenterHorizontally,
    rightIconHorizontalArrangementButtonTypeStandard = Arrangement.Center,
    buttonIcon2WidthButtonTypeStandardSizeLarge = DSVariables.sizingComponent10,
    buttonIcon2WidthButtonTypeStandardSizeSmall = DSVariables.sizingComponent7,
    buttonIcon2HeightButtonTypeStandardSizeLarge = DSVariables.sizingComponent10,
    buttonIcon2HeightButtonTypeStandardSizeSmall = DSVariables.sizingComponent7,
    buttonIcon3WidthButtonTypeIconOnlySizeLarge = DSVariables.sizingComponent10,
    buttonIcon3WidthButtonTypeIconOnlySizeSmall = DSVariables.sizingComponent7,
    buttonIcon3HeightButtonTypeIconOnlySizeLarge = DSVariables.sizingComponent10,
    buttonIcon3HeightButtonTypeIconOnlySizeSmall = DSVariables.sizingComponent7,
    scaleFactor = SCALE_FACTOR,
    buttonLabelTextOverflow = TextOverflow.Ellipsis
)

var DSButtonTokens: ODSButtonTokens = defaultODSButtonTokens
