package com.telekom.odsystem.componenttokens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import com.telekom.odsystem.DSTextStyles
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSTextStyle

@Suppress("LongParameterList")
class ODSProgressBarTokens(
    var gap: Dp,
    var minWidth: Dp,
    var verticalAlignment: Alignment.Vertical,
    var horizontalAlignment: Alignment.Horizontal,
    var verticalArrangement: Arrangement.Vertical,
    var dataGap: Dp,
    var dataClipContent: Boolean,
    var dataVerticalAlignment: Alignment.Vertical,
    var dataHorizontalAlignment: Alignment.Horizontal,
    var dataHorizontalArrangement: Arrangement.Horizontal,
    var mainDataGap: Dp,
    var mainDataVerticalAlignment: Alignment.Vertical,
    var mainDataHorizontalAlignment: Alignment.Horizontal,
    var mainDataVerticalArrangement: Arrangement.Vertical,
    var mainDataTextGap: Dp,
    var mainDataTextVerticalAlignment: Alignment.Vertical,
    var mainDataTextHorizontalAlignment: Alignment.Horizontal,
    var mainDataTextHorizontalArrangement: Arrangement.Horizontal,
    var dataProgressTrackContainerVerticalAlignment: Alignment.Vertical,
    var dataProgressTrackContainerHorizontalAlignment: Alignment.Horizontal,
    var dataProgressTrackContainerVerticalArrangement: Arrangement.Vertical,
    var extraDataGap: Dp,
    var extraDataWidth: Dp,
    var extraDataVerticalAlignment: Alignment.Vertical,
    var extraDataHorizontalAlignment: Alignment.Horizontal,
    var extraDataVerticalArrangement: Arrangement.Vertical,
    var extraDataTextVerticalAlignment: Alignment.Vertical,
    var extraDataTextHorizontalAlignment: Alignment.Horizontal,
    var extraDataTextHorizontalArrangement: Arrangement.Horizontal,
    var extraDataProgressTrackContainerHeightSizeSmall: Dp,
    var extraDataProgressTrackContainerHeightSizeMedium: Dp,
    var extraDataProgressTrackContainerHeightSizeLarge: Dp,
    var extraDataProgressTrackContainerVerticalAlignment: Alignment.Vertical,
    var extraDataProgressTrackContainerHorizontalAlignment: Alignment.Horizontal,
    var extraDataProgressTrackContainerVerticalArrangement: Arrangement.Vertical,
    var dataWarningWidthStatusError: Dp,
    var dataWarningHeightStatusError: Dp,
    var extraDataWarningWidthStatusError: Dp,
    var extraDataWarningHeightStatusError: Dp,
    var dataSuccessWidthStatusSuccess: Dp,
    var dataSuccessHeightStatusSuccess: Dp,
    var extraDataSuccessWidthStatusSuccess: Dp,
    var extraDataSuccessHeightStatusSuccess: Dp,
    var labelTextTextStyle: ODSTextStyle,
    var labelTextTextAlign: TextAlign,
    var labelTextTextOverflow: TextOverflow,
    var counterTextTextStyleStatusStandard: ODSTextStyle,
    var counterTextTextAlignStatusStandard: TextAlign,
    var counterTextTextOverflowStatusStandard: TextOverflow,
    var extraDataTextTextStyleStatusStandard: ODSTextStyle,
    var extraDataTextTextAlignStatusStandard: TextAlign,
    var extraDataTextTextOverflowStatusStandard: TextOverflow,
    var helperTextTextStyle: ODSTextStyle,
    var helperTextTextAlign: TextAlign
)

var defaultODSProgressBarTokens = ODSProgressBarTokens(
    gap = DSVariables.spacingComponent2,
    minWidth = DSVariables.sizingComponent20,
    verticalAlignment = Alignment.Top,
    horizontalAlignment = Alignment.Start,
    verticalArrangement = Arrangement.Top,
    dataGap = DSVariables.spacingComponent2,
    dataClipContent = true,
    dataVerticalAlignment = Alignment.Bottom,
    dataHorizontalAlignment = Alignment.Start,
    dataHorizontalArrangement = Arrangement.Start,
    mainDataGap = DSVariables.spacingComponent2,
    mainDataVerticalAlignment = Alignment.Top,
    mainDataHorizontalAlignment = Alignment.Start,
    mainDataVerticalArrangement = Arrangement.Top,
    mainDataTextGap = DSVariables.spacingComponent5,
    mainDataTextVerticalAlignment = Alignment.Bottom,
    mainDataTextHorizontalAlignment = Alignment.Start,
    mainDataTextHorizontalArrangement = Arrangement.Start,
    dataProgressTrackContainerVerticalAlignment = Alignment.Top,
    dataProgressTrackContainerHorizontalAlignment = Alignment.Start,
    dataProgressTrackContainerVerticalArrangement = Arrangement.Top,
    extraDataGap = DSVariables.spacingComponent2,
    extraDataWidth = DSVariables.sizingComponent16,
    extraDataVerticalAlignment = Alignment.Top,
    extraDataHorizontalAlignment = Alignment.Start,
    extraDataVerticalArrangement = Arrangement.Top,
    extraDataTextVerticalAlignment = Alignment.Top,
    extraDataTextHorizontalAlignment = Alignment.End,
    extraDataTextHorizontalArrangement = Arrangement.End,
    extraDataProgressTrackContainerHeightSizeSmall = DSVariables.sizingComponent4,
    extraDataProgressTrackContainerHeightSizeMedium = DSVariables.sizingComponent7,
    extraDataProgressTrackContainerHeightSizeLarge = DSVariables.sizingComponent14,
    extraDataProgressTrackContainerVerticalAlignment = Alignment.Top,
    extraDataProgressTrackContainerHorizontalAlignment = Alignment.Start,
    extraDataProgressTrackContainerVerticalArrangement = Arrangement.Top,
    dataWarningWidthStatusError = DSVariables.sizingComponent7,
    dataWarningHeightStatusError = DSVariables.sizingComponent7,
    extraDataWarningWidthStatusError = DSVariables.sizingComponent7,
    extraDataWarningHeightStatusError = DSVariables.sizingComponent7,
    dataSuccessWidthStatusSuccess = DSVariables.sizingComponent7,
    dataSuccessHeightStatusSuccess = DSVariables.sizingComponent7,
    extraDataSuccessWidthStatusSuccess = DSVariables.sizingComponent7,
    extraDataSuccessHeightStatusSuccess = DSVariables.sizingComponent7,
    labelTextTextStyle = DSTextStyles.microcopyBold,
    labelTextTextAlign = TextAlign.Left,
    labelTextTextOverflow = TextOverflow.Ellipsis,
    counterTextTextStyleStatusStandard = DSTextStyles.microcopyBold,
    counterTextTextAlignStatusStandard = TextAlign.Right,
    counterTextTextOverflowStatusStandard = TextOverflow.Ellipsis,
    extraDataTextTextStyleStatusStandard = DSTextStyles.microcopyBold,
    extraDataTextTextAlignStatusStandard = TextAlign.Right,
    extraDataTextTextOverflowStatusStandard = TextOverflow.Ellipsis,
    helperTextTextStyle = DSTextStyles.microcopyBold,
    helperTextTextAlign = TextAlign.Left
)

var DSProgressBarTokens: ODSProgressBarTokens = defaultODSProgressBarTokens
