// This file is auto-generated. DO NOT EDIT. All changes will be lost.

package com.telekom.odsystem.tokens.tokens

import com.telekom.odsystem.foundations.HexColor
import com.telekom.odsystem.foundations.ODSEffect
import kotlinx.serialization.Serializable

@Serializable
data class ODSTheme(
    val name: String,
    val basicAccent: HexColor,
    val basicAccentSecondary: HexColor,
    val basicBackground: HexColor,
    val basicBackgroundCard: HexColor,
    val basicBackgroundCardSubtle: HexColor,
    val basicBackgroundSubtle: HexColor,
    val basicModalOverlay: HexColor,
    val basicStroke: HexColor,
    val basicStrokeSubtle: HexColor,
    val basicText: HexColor,
    val basicTextDominant: HexColor,
    val basicTextLink: HexColor,
    val basicTextOnAccent: HexColor,
    val basicTextOnAccentSecondary: HexColor,
    val basicTextRecessive: HexColor,
    val elevationAppBarBottomFlatColour: HexColor,
    val elevationAppBarBottomRaisedColour: HexColor,
    val elevationAppBarTopFlatColour: HexColor,
    val elevationAppBarTopRaisedColour: HexColor,
    val elevationFabHoveredColour: HexColor,
    val elevationFabPressedColour: HexColor,
    val elevationFabStandardColour: HexColor,
    val elevationLevel0Colour: HexColor,
    val elevationLevel1Colour: HexColor,
    val elevationLevel2Colour: HexColor,
    val elevationLevel3Colour: HexColor,
    val elevationLevel4Colour: HexColor,
    val elevationLevel5Colour: HexColor,
    val elevationLevel6Colour: HexColor,
    val functionalDestructiveHovered: HexColor,
    val functionalDestructivePressed: HexColor,
    val functionalDestructiveStandard: HexColor,
    val functionalDestructiveSubtle: HexColor,
    val functionalInformationalHovered: HexColor,
    val functionalInformationalPressed: HexColor,
    val functionalInformationalStandard: HexColor,
    val functionalInformationalSubtle: HexColor,
    val functionalNotificationNotification: HexColor,
    val functionalNotificationTextOnNotification: HexColor,
    val functionalSuccessHovered: HexColor,
    val functionalSuccessPressed: HexColor,
    val functionalSuccessStandard: HexColor,
    val functionalSuccessSubtle: HexColor,
    val functionalWarningHovered: HexColor,
    val functionalWarningPressed: HexColor,
    val functionalWarningStandard: HexColor,
    val functionalWarningSubtle: HexColor,
    val interactionStatesDisabledAccentDisabled: HexColor,
    val interactionStatesDisabledAccentSecondaryDisabled: HexColor,
    val interactionStatesDisabledBackgroundCardDisabled: HexColor,
    val interactionStatesDisabledBackgroundDisabled: HexColor,
    val interactionStatesDisabledBackgroundSubtleDisabled: HexColor,
    val interactionStatesDisabledStrokeDisabled: HexColor,
    val interactionStatesDisabledStrokeSubtleDisabled: HexColor,
    val interactionStatesDisabledTextDisabled: HexColor,
    val interactionStatesDisabledTextDominantDisabled: HexColor,
    val interactionStatesDisabledTextLinkDisabled: HexColor,
    val interactionStatesDisabledTextOnAccentDisabled: HexColor,
    val interactionStatesDisabledTextOnAccentSecondaryDisabled: HexColor,
    val interactionStatesDisabledTextRecessiveDisabled: HexColor,
    val interactionStatesFocusFocus: HexColor,
    val interactionStatesFocusStrokeActive: HexColor,
    val interactionStatesHoverAccentHover: HexColor,
    val interactionStatesHoverAccentSecondaryHover: HexColor,
    val interactionStatesHoverBackgroundHover: HexColor,
    val interactionStatesHoverBackgroundSubtleHover: HexColor,
    val interactionStatesHoverStrokeHover: HexColor,
    val interactionStatesHoverStrokeSubtleHover: HexColor,
    val interactionStatesHoverTextDominantHover: HexColor,
    val interactionStatesHoverTextHover: HexColor,
    val interactionStatesHoverTextLinkHover: HexColor,
    val interactionStatesHoverTextOnAccentHover: HexColor,
    val interactionStatesHoverTextOnAccentSecondaryHover: HexColor,
    val interactionStatesHoverTextRecessiveHover: HexColor,
    val interactionStatesPressedAccentPressed: HexColor,
    val interactionStatesPressedAccentSecondaryPressed: HexColor,
    val interactionStatesPressedBackgroundPressed: HexColor,
    val interactionStatesPressedBackgroundSubtlePressed: HexColor,
    val interactionStatesPressedStrokePressed: HexColor,
    val interactionStatesPressedStrokeSubtlePressed: HexColor,
    val interactionStatesPressedTextDominantPressed: HexColor,
    val interactionStatesPressedTextLinkPressed: HexColor,
    val interactionStatesPressedTextOnAccentPressed: HexColor,
    val interactionStatesPressedTextOnAccentSecondaryPressed: HexColor,
    val interactionStatesPressedTextPressed: HexColor,
    val interactionStatesPressedTextRecessivePressed: HexColor,
    val interactionStatesVisitedTextLinkVisited: HexColor,
    val interactionStatesVisitedTextVisited: HexColor,
    val shadesAccentShadesAccentDominant: HexColor,
    val shadesAccentShadesAccentExtraDominant: HexColor,
    val shadesAccentShadesAccentExtraRecessive: HexColor,
    val shadesAccentShadesAccentRecessive: HexColor,
    val shadesAccentShadesAccentSubtle: HexColor,
    val shadesNeutralShades100: HexColor,
    val shadesNeutralShades200: HexColor,
    val shadesNeutralShades300: HexColor,
    val shadesNeutralShades400: HexColor,
    val shadesNeutralShades500: HexColor,
    val shadesNeutralShades600: HexColor,
    val shadesNeutralShades700: HexColor,
    val shadesNeutralShades800: HexColor,
    val shadesNeutralShades900: HexColor,
    val shadesSecondaryAccentShadesSecondaryAccentDominant: HexColor,
    val shadesSecondaryAccentShadesSecondaryAccentExtraDominant: HexColor,
    val shadesSecondaryAccentShadesSecondaryAccentExtraRecessive: HexColor,
    val shadesSecondaryAccentShadesSecondaryAccentRecessive: HexColor,
    val shadesSecondaryAccentShadesSecondaryAccentSubtle: HexColor,
    val elevationAppBarBottomFlat: ODSEffect,
    val elevationAppBarBottomRaised: ODSEffect,
    val elevationAppBarTopFlat: ODSEffect,
    val elevationAppBarTopRaised: ODSEffect,
    val elevationFabHovered: ODSEffect,
    val elevationFabPressed: ODSEffect,
    val elevationFabStandard: ODSEffect,
    val elevationLevel0: ODSEffect,
    val elevationLevel1: ODSEffect,
    val elevationLevel2: ODSEffect,
    val elevationLevel3: ODSEffect,
    val elevationLevel4: ODSEffect,
    val elevationLevel5: ODSEffect,
    val elevationLevel6: ODSEffect
)

val allSchemes = listOf(
    blackScheme,
    magentaScheme,
    whiteScheme,
    aperitifSecondaryScheme,
    basketballSecondaryScheme,
    cheddarSecondaryScheme,
    dandelionSecondaryScheme,
    eggSecondaryScheme,
    frogSecondaryScheme,
    guacamoleSecondaryScheme,
    hummingbirdSecondaryScheme,
    iguanaSecondaryScheme,
    jacuzziSecondaryScheme,
    kingfisherSecondaryScheme,
    lagoonSecondaryScheme,
    macawSecondaryScheme,
    nebulaSecondaryScheme,
    orchidSecondaryScheme,
)

