package com.telekom.odsystem.atoms.textfield

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSTextStyles
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSCorners
import com.telekom.odsystem.foundations.ODSPadding
import com.telekom.odsystem.foundations.ODSTextStyle

/**
 * Code generated with ODS RADD Code Generator
 * 2025-07-31 (v1.32.3) - uid: a7adc77
 * Figma link: https://figma.com/design/9DAhZcVWjS2WXQjpYkC6D5/OneID Expl_Concept Topics?node-id=5982-20892
 */

data class ODSTextFieldTokens(
    val gap: Dp,
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignment: Alignment.Horizontal,
    val verticalArrangement: Arrangement.Vertical,
    val inputFieldPadding: ODSPadding,
    val inputFieldCornerRadius: ODSCorners,
    val inputFieldBorderModeStandard: Dp,
    val inputFieldBorderModeInformative: Dp,
    val inputFieldBorderModeError: Dp,
    val inputFieldMinHeightSizeLarge: Dp,
    val inputFieldMinHeightSizeSmall: Dp,
    val inputFieldClipContent: Boolean,
    val inputFieldVerticalAlignment: Alignment.Vertical,
    val inputFieldHorizontalAlignment: Alignment.Horizontal,
    val inputFieldHorizontalArrangement: Arrangement.Horizontal,
    val contentGapSizeLarge: Dp,
    val contentPadding: ODSPadding,
    val contentVerticalAlignment: Alignment.Vertical,
    val contentHorizontalAlignment: Alignment.Horizontal,
    val contentVerticalArrangement: Arrangement.Vertical,
    val eyebrowGap: Dp,
    val eyebrowVerticalAlignment: Alignment.Vertical,
    val eyebrowHorizontalAlignment: Alignment.Horizontal,
    val eyebrowHorizontalArrangement: Arrangement.Horizontal,
    val labelStyleSizeLarge: ODSTextStyle,
    val labelStyleSizeSmall: ODSTextStyle,
    val labelStyleSizeLargeShowPlaceholder: ODSTextStyle,
    val labelStyleSizeLargeFilled: ODSTextStyle,
    val labelStyleSizeSmallShowPlaceholder: ODSTextStyle,
    val labelStyleSizeSmallFilled: ODSTextStyle,
    val labelTextAlign: TextAlign,
    val labelMaxLines: Int,
    val requiredStyleSizeLarge: ODSTextStyle,
    val requiredStyleSizeSmall: ODSTextStyle,
    val requiredStyleSizeLargeShowPlaceholder: ODSTextStyle,
    val requiredStyleSizeLargeFilled: ODSTextStyle,
    val requiredStyleSizeSmallShowPlaceholder: ODSTextStyle,
    val requiredStyleSizeSmallFilled: ODSTextStyle,
    val requiredTextAlign: TextAlign,
    val inputGap: Dp,
    val inputVerticalAlignment: Alignment.Vertical,
    val inputHorizontalAlignment: Alignment.Horizontal,
    val inputHorizontalArrangement: Arrangement.Horizontal,
    val leftIconWidthSizeLarge: Dp,
    val leftIconWidthSizeSmall: Dp,
    val leftIconHeightSizeLarge: Dp,
    val leftIconHeightSizeSmall: Dp,
    val prefixStyleSizeLarge: ODSTextStyle,
    val prefixStyleSizeSmall: ODSTextStyle,
    val prefixTextAlign: TextAlign,
    val cursorGroupVerticalAlignment: Alignment.Vertical,
    val cursorGroupHorizontalAlignment: Alignment.Horizontal,
    val cursorGroupHorizontalArrangement: Arrangement.Horizontal,
    val cursorGroupGapModeStandardShowPlaceholder: Dp,
    val inputValueStyleSizeLarge: ODSTextStyle,
    val inputValueStyleSizeLargeShowPlaceholderFilled: ODSTextStyle,
    val inputValueStyleSizeSmall: ODSTextStyle,
    val inputValueStyleSizeSmallShowPlaceholderFilled: ODSTextStyle,
    val inputValueTextAlign: TextAlign,
    val inputValueTextAlignShowPlaceholderFilled: TextAlign,
    val inputValueOverflow: TextOverflow,
    val inputValueOverflowShowPlaceholderFilled: TextOverflow,
    val inputValueMaxLines: Int,
    val inputValueMaxLinesShowPlaceholderFilled: Int,
    val placeholderStyleSizeLargeShowPlaceholder: ODSTextStyle,
    val placeholderStyleSizeSmallShowPlaceholder: ODSTextStyle,
    val placeholderTextAlignShowPlaceholder: TextAlign,
    val placeholderOverflowShowPlaceholder: TextOverflow,
    val placeholderMaxLinesShowPlaceholder: Int,
    val suffixStyleSizeLarge: ODSTextStyle,
    val suffixStyleSizeSmall: ODSTextStyle,
    val suffixTextAlign: TextAlign,
    val iconContainerPadding: ODSPadding,
    val iconContainerWidth: Dp,
    val iconContainerHeight: Dp,
    val iconContainerVerticalAlignment: Alignment.Vertical,
    val iconContainerHorizontalAlignment: Alignment.Horizontal,
    val iconContainerHorizontalArrangement: Arrangement.Horizontal,
    val rightIconWidthSizeLarge: Dp,
    val rightIconWidthSizeSmall: Dp,
    val rightIconHeightSizeLarge: Dp,
    val rightIconHeightSizeSmall: Dp,
    val supportTextPadding: ODSPadding,
    val supportTextVerticalAlignment: Alignment.Vertical,
    val supportTextHorizontalAlignment: Alignment.Horizontal,
    val supportTextHorizontalArrangement: Arrangement.Horizontal,
    val counterStyle: ODSTextStyle,
    val counterTextAlign: TextAlign,
    val counterWidth: Dp, // Not used in mobile
    var contentContainerAlignment: Alignment, // Not exported from the plugin
)

val defaultODSTextFieldTokens = ODSTextFieldTokens(
    gap = DSVariables.spacingComponent3,
    verticalAlignment = Alignment.Top,
    horizontalAlignment = Alignment.Start,
    verticalArrangement = Arrangement.Top,
    inputFieldPadding = ODSPadding(
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent5
    ),
    inputFieldCornerRadius = ODSCorners(all = DSVariables.radiusMedium),
    inputFieldBorderModeStandard = DSVariables.strokes1,
    inputFieldBorderModeInformative = DSVariables.strokes1,
    inputFieldBorderModeError = DSVariables.strokes3,
    inputFieldMinHeightSizeLarge = DSVariables.sizingInputHeight,
    inputFieldMinHeightSizeSmall = 58.dp,
    inputFieldClipContent = true,
    inputFieldVerticalAlignment = Alignment.CenterVertically,
    inputFieldHorizontalAlignment = Alignment.Start,
    inputFieldHorizontalArrangement = Arrangement.Start,
    contentGapSizeLarge = DSVariables.spacingComponent1,
    contentPadding = ODSPadding(right = DSVariables.spacingComponent4),
    contentVerticalAlignment = Alignment.CenterVertically,
    contentHorizontalAlignment = Alignment.Start,
    contentVerticalArrangement = Arrangement.Center,
    eyebrowGap = DSVariables.spacingComponent1,
    eyebrowVerticalAlignment = Alignment.CenterVertically,
    eyebrowHorizontalAlignment = Alignment.Start,
    eyebrowHorizontalArrangement = Arrangement.Start,
    labelStyleSizeLarge = DSTextStyles.subtitle,
    labelStyleSizeSmall = DSTextStyles.bodyMBold,
    labelStyleSizeLargeShowPlaceholder = DSTextStyles.bodyMBold,
    labelStyleSizeLargeFilled = DSTextStyles.bodyMBold,
    labelStyleSizeSmallShowPlaceholder = DSTextStyles.bodySBold,
    labelStyleSizeSmallFilled = DSTextStyles.bodySBold,
    labelTextAlign = TextAlign.Left,
    labelMaxLines = 1,
    requiredStyleSizeLarge = DSTextStyles.subtitle,
    requiredStyleSizeSmall = DSTextStyles.bodyMBold,
    requiredStyleSizeLargeShowPlaceholder = DSTextStyles.bodyMBold,
    requiredStyleSizeLargeFilled = DSTextStyles.bodyMBold,
    requiredStyleSizeSmallShowPlaceholder = DSTextStyles.bodySBold,
    requiredStyleSizeSmallFilled = DSTextStyles.bodySBold,
    requiredTextAlign = TextAlign.Left,
    inputGap = DSVariables.spacingComponent3,
    inputVerticalAlignment = Alignment.Bottom,
    inputHorizontalAlignment = Alignment.Start,
    inputHorizontalArrangement = Arrangement.Start,
    leftIconWidthSizeLarge = DSVariables.sizingComponent10,
    leftIconWidthSizeSmall = DSVariables.sizingComponent8,
    leftIconHeightSizeLarge = DSVariables.sizingComponent10,
    leftIconHeightSizeSmall = DSVariables.sizingComponent8,
    prefixStyleSizeLarge = DSTextStyles.subtitle,
    prefixStyleSizeSmall = DSTextStyles.bodyMBold,
    prefixTextAlign = TextAlign.Left,
    cursorGroupVerticalAlignment = Alignment.CenterVertically,
    cursorGroupHorizontalAlignment = Alignment.Start,
    cursorGroupHorizontalArrangement = Arrangement.Start,
    cursorGroupGapModeStandardShowPlaceholder = DSVariables.spacingComponent1,
    inputValueStyleSizeLarge = DSTextStyles.subtitle,
    inputValueStyleSizeLargeShowPlaceholderFilled = DSTextStyles.subtitle,
    inputValueStyleSizeSmall = DSTextStyles.bodyMBold,
    inputValueStyleSizeSmallShowPlaceholderFilled = DSTextStyles.bodyMBold,
    inputValueTextAlign = TextAlign.Left,
    inputValueTextAlignShowPlaceholderFilled = TextAlign.Left,
    inputValueOverflow = TextOverflow.Ellipsis,
    inputValueOverflowShowPlaceholderFilled = TextOverflow.Ellipsis,
    inputValueMaxLines = 1,
    inputValueMaxLinesShowPlaceholderFilled = 1,
    placeholderStyleSizeLargeShowPlaceholder = DSTextStyles.subtitle,
    placeholderStyleSizeSmallShowPlaceholder = DSTextStyles.bodyMBold,
    placeholderTextAlignShowPlaceholder = TextAlign.Left,
    placeholderOverflowShowPlaceholder = TextOverflow.Ellipsis,
    placeholderMaxLinesShowPlaceholder = 1,
    suffixStyleSizeLarge = DSTextStyles.subtitle,
    suffixStyleSizeSmall = DSTextStyles.bodyMBold,
    suffixTextAlign = TextAlign.Right,
    iconContainerPadding = ODSPadding(
        left = DSVariables.spacingComponent4,
        right = DSVariables.spacingComponent4
    ),
    iconContainerWidth = DSVariables.sizingComponent14,
    iconContainerHeight = DSVariables.sizingComponent14,
    iconContainerVerticalAlignment = Alignment.CenterVertically,
    iconContainerHorizontalAlignment = Alignment.CenterHorizontally,
    iconContainerHorizontalArrangement = Arrangement.Center,
    rightIconWidthSizeLarge = 24.dp,
    rightIconWidthSizeSmall = DSVariables.sizingComponent8,
    rightIconHeightSizeLarge = 24.dp,
    rightIconHeightSizeSmall = DSVariables.sizingComponent8,
    supportTextPadding = ODSPadding(left = DSVariables.spacingComponent7),
    supportTextVerticalAlignment = Alignment.Top,
    supportTextHorizontalAlignment = Alignment.End,
    supportTextHorizontalArrangement = Arrangement.End,
    counterStyle = DSTextStyles.bodySRegular,
    counterTextAlign = TextAlign.Right,
    counterWidth = 80.dp,
    contentContainerAlignment = Alignment.CenterStart
)

var DSTextFieldTokens: ODSTextFieldTokens = defaultODSTextFieldTokens
