package com.telekom.odsystem.organisms.pageheader

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.unit.Dp
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSPadding

/**
 * Code generated with ODS RADD Code Generator
 * 2025-10-20 (v1.33.1) - uid: 22537e02
 * Figma link: https://figma.com/design/cpaNsDgmzEjyHilbYDSKS9/Exploration File_Part 2?node-id=7221-141590
 */
data class ODSPageHeaderTokens(
    val gap: Dp,
    val padding: ODSPadding,
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignment: Alignment.Horizontal,
    val verticalArrangement: Arrangement.Vertical,
    val mainPageHeaderTopSectionPaddingTypeMainPageHeaderStandard: ODSPadding,
    val mainPageHeaderTopSectionPaddingTypeMainPageHeaderSlim: ODSPadding,
    val mainPageHeaderTopSectionHeightTypeMainPageHeaderStandard: Dp,
    val mainPageHeaderTopSectionHeightTypeMainPageHeaderSlim: Dp,
    val mainPageHeaderTopSectionVerticalAlignmentTypeMainPageHeaderStandard: Alignment.Vertical,
    val mainPageHeaderTopSectionVerticalAlignmentTypeMainPageHeaderSlim: Alignment.Vertical,
    val mainPageHeaderTopSectionHorizontalArrangementTypeMainPageHeaderStandard: Arrangement.Horizontal,
    val mainPageHeaderTopSectionHorizontalArrangementTypeMainPageHeaderSlim: Arrangement.Horizontal,
    val logoSlotContainerWidthTypeMainPageHeaderStandard: Dp,
    val logoSlotContainerWidthTypeMainPageHeaderSlim: Dp,
    val logoSlotContainerHeightTypeMainPageHeaderStandard: Dp,
    val logoSlotContainerHeightTypeMainPageHeaderSlim: Dp,
    val logoSlotContainerVerticalAlignmentTypeMainPageHeaderStandard: Alignment.Vertical,
    val logoSlotContainerVerticalAlignmentTypeMainPageHeaderSlim: Alignment.Vertical,
    val logoSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard: Alignment.Horizontal,
    val logoSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim: Alignment.Horizontal,
    val logoSlotContainerVerticalArrangementTypeMainPageHeaderStandard: Arrangement.Vertical,
    val logoSlotContainerVerticalArrangementTypeMainPageHeaderSlim: Arrangement.Vertical,
    val topSectionMainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderStandard: Alignment.Vertical,
    val topSectionMainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderSlim: Alignment.Vertical,
    val topSectionMainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard: Alignment.Horizontal,
    val topSectionMainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim: Alignment.Horizontal,
    val topSectionMainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderStandard: Arrangement.Vertical,
    val topSectionMainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderSlim: Arrangement.Vertical,
    val preferredActionsSlotContainerMinWidthTypeMainPageHeaderStandard: Dp,
    val preferredActionsSlotContainerMinWidthTypeMainPageHeaderSlim: Dp,
    val preferredActionsSlotContainerVerticalAlignmentTypeMainPageHeaderStandard: Alignment.Vertical,
    val preferredActionsSlotContainerVerticalAlignmentTypeMainPageHeaderSlim: Alignment.Vertical,
    val preferredActionsSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard: Alignment.Horizontal,
    val preferredActionsSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim: Alignment.Horizontal,
    val preferredActionsSlotContainerVerticalArrangementTypeMainPageHeaderStandard: Arrangement.Vertical,
    val preferredActionsSlotContainerVerticalArrangementTypeMainPageHeaderSlim: Arrangement.Vertical,
    val mainPageTitleSlotContainerPaddingTypeMainPageHeaderStandard: ODSPadding,
    val mainPageTitleSlotContainerPaddingTypeMainPageHeaderSlim: ODSPadding,
    val mainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderStandard: Alignment.Vertical,
    val mainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderSlim: Alignment.Vertical,
    val mainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard: Alignment.Horizontal,
    val mainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim: Alignment.Horizontal,
    val mainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderStandard: Arrangement.Vertical,
    val mainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderSlim: Arrangement.Vertical,
    val tabsContainerGap: Dp,
    val tabsContainerPadding: ODSPadding,
    val tabsContainerVerticalAlignment: Alignment.Vertical,
    val tabsContainerHorizontalAlignment: Alignment.Horizontal,
    val tabsContainerVerticalArrangement: Arrangement.Vertical,
    val dividerContainerHeight: Dp,
    val dividerContainerVerticalAlignment: Alignment.Vertical,
    val dividerContainerHorizontalAlignment: Alignment.Horizontal,
    val dividerContainerVerticalArrangement: Arrangement.Vertical,
    val subPageHeaderTopSectionPaddingTypeSubPageHeader: ODSPadding,
    val subPageHeaderTopSectionHeightTypeSubPageHeader: Dp,
    val subPageHeaderTopSectionVerticalAlignmentTypeSubPageHeader: Alignment.Vertical,
    val subPageHeaderTopSectionHorizontalArrangementTypeSubPageHeader: Arrangement.Horizontal,
    val subPageTitleSlotContainerGapTypeSubPageHeader: Dp,
    val subPageTitleSlotContainerVerticalAlignmentTypeSubPageHeader: Alignment.Vertical,
    val subPageTitleSlotContainerHorizontalAlignmentTypeSubPageHeader: Alignment.Horizontal,
    val subPageTitleSlotContainerVerticalArrangementTypeSubPageHeader: Arrangement.Vertical,
    val preferredActionsSlotContainer2MinWidthTypeSubPageHeader: Dp,
    val preferredActionsSlotContainer2VerticalAlignmentTypeSubPageHeader: Alignment.Vertical,
    val preferredActionsSlotContainer2HorizontalAlignmentTypeSubPageHeader: Alignment.Horizontal,
    val preferredActionsSlotContainer2VerticalArrangementTypeSubPageHeader: Arrangement.Vertical,
)

val defaultODSPageHeaderTokens = ODSPageHeaderTokens(
    gap = DSVariables.spacingComponent0,
    padding = ODSPadding(
        left = DSVariables.spacingComponent0,
        right = DSVariables.spacingComponent0
    ),
    verticalAlignment = Alignment.Top,
    horizontalAlignment = Alignment.Start,
    verticalArrangement = Arrangement.Top,
    mainPageHeaderTopSectionPaddingTypeMainPageHeaderStandard = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent7
    ),
    mainPageHeaderTopSectionPaddingTypeMainPageHeaderSlim = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent7
    ),
    mainPageHeaderTopSectionHeightTypeMainPageHeaderStandard = DSVariables.sizingComponent17,
    mainPageHeaderTopSectionHeightTypeMainPageHeaderSlim = DSVariables.sizingComponent17,
    mainPageHeaderTopSectionVerticalAlignmentTypeMainPageHeaderStandard = Alignment.CenterVertically,
    mainPageHeaderTopSectionVerticalAlignmentTypeMainPageHeaderSlim = Alignment.CenterVertically,
    mainPageHeaderTopSectionHorizontalArrangementTypeMainPageHeaderStandard = Arrangement.SpaceBetween,
    mainPageHeaderTopSectionHorizontalArrangementTypeMainPageHeaderSlim = Arrangement.SpaceBetween,
    logoSlotContainerWidthTypeMainPageHeaderStandard = DSVariables.sizingMinimumTappableArea,
    logoSlotContainerWidthTypeMainPageHeaderSlim = DSVariables.sizingMinimumTappableArea,
    logoSlotContainerHeightTypeMainPageHeaderStandard = DSVariables.sizingMinimumTappableArea,
    logoSlotContainerHeightTypeMainPageHeaderSlim = DSVariables.sizingMinimumTappableArea,
    logoSlotContainerVerticalAlignmentTypeMainPageHeaderStandard = Alignment.Top,
    logoSlotContainerVerticalAlignmentTypeMainPageHeaderSlim = Alignment.Top,
    logoSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard = Alignment.Start,
    logoSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim = Alignment.Start,
    logoSlotContainerVerticalArrangementTypeMainPageHeaderStandard = Arrangement.Top,
    logoSlotContainerVerticalArrangementTypeMainPageHeaderSlim = Arrangement.Top,
    topSectionMainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderStandard = Alignment.Top,
    topSectionMainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderSlim = Alignment.Top,
    topSectionMainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard = Alignment.Start,
    topSectionMainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim = Alignment.Start,
    topSectionMainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderStandard = Arrangement.Top,
    topSectionMainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderSlim = Arrangement.Top,
    preferredActionsSlotContainerMinWidthTypeMainPageHeaderStandard = DSVariables.sizingMinimumTappableArea,
    preferredActionsSlotContainerMinWidthTypeMainPageHeaderSlim = DSVariables.sizingMinimumTappableArea,
    preferredActionsSlotContainerVerticalAlignmentTypeMainPageHeaderStandard = Alignment.CenterVertically,
    preferredActionsSlotContainerVerticalAlignmentTypeMainPageHeaderSlim = Alignment.CenterVertically,
    preferredActionsSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard = Alignment.End,
    preferredActionsSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim = Alignment.End,
    preferredActionsSlotContainerVerticalArrangementTypeMainPageHeaderStandard = Arrangement.Center,
    preferredActionsSlotContainerVerticalArrangementTypeMainPageHeaderSlim = Arrangement.Center,
    mainPageTitleSlotContainerPaddingTypeMainPageHeaderStandard = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent7
    ),
    mainPageTitleSlotContainerPaddingTypeMainPageHeaderSlim = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent7
    ),
    mainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderStandard = Alignment.Top,
    mainPageTitleSlotContainerVerticalAlignmentTypeMainPageHeaderSlim = Alignment.Top,
    mainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderStandard = Alignment.Start,
    mainPageTitleSlotContainerHorizontalAlignmentTypeMainPageHeaderSlim = Alignment.Start,
    mainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderStandard = Arrangement.Top,
    mainPageTitleSlotContainerVerticalArrangementTypeMainPageHeaderSlim = Arrangement.Top,
    tabsContainerGap = DSVariables.spacingComponent0,
    tabsContainerPadding = ODSPadding(
        bottom = DSVariables.spacingComponent3,
        left = DSVariables.spacingComponent7,
        right = DSVariables.spacingComponent0
    ),
    tabsContainerVerticalAlignment = Alignment.Top,
    tabsContainerHorizontalAlignment = Alignment.Start,
    tabsContainerVerticalArrangement = Arrangement.Top,
    dividerContainerHeight = DSVariables.sizingComponent1,
    dividerContainerVerticalAlignment = Alignment.Top,
    dividerContainerHorizontalAlignment = Alignment.Start,
    dividerContainerVerticalArrangement = Arrangement.Top,
    subPageHeaderTopSectionPaddingTypeSubPageHeader = ODSPadding(
        top = DSVariables.spacingComponent5,
        bottom = DSVariables.spacingComponent5,
        left = DSVariables.spacingComponent5,
        right = DSVariables.spacingComponent7
    ),
    subPageHeaderTopSectionHeightTypeSubPageHeader = DSVariables.sizingComponent17,
    subPageHeaderTopSectionVerticalAlignmentTypeSubPageHeader = Alignment.CenterVertically,
    subPageHeaderTopSectionHorizontalArrangementTypeSubPageHeader = Arrangement.SpaceBetween,
    subPageTitleSlotContainerGapTypeSubPageHeader = DSVariables.spacingComponent0,
    subPageTitleSlotContainerVerticalAlignmentTypeSubPageHeader = Alignment.Top,
    subPageTitleSlotContainerHorizontalAlignmentTypeSubPageHeader = Alignment.Start,
    subPageTitleSlotContainerVerticalArrangementTypeSubPageHeader = Arrangement.Top,
    preferredActionsSlotContainer2MinWidthTypeSubPageHeader = DSVariables.sizingMinimumTappableArea,
    preferredActionsSlotContainer2VerticalAlignmentTypeSubPageHeader = Alignment.CenterVertically,
    preferredActionsSlotContainer2HorizontalAlignmentTypeSubPageHeader = Alignment.End,
    preferredActionsSlotContainer2VerticalArrangementTypeSubPageHeader = Arrangement.Center
)

var DSPageHeaderTokens: ODSPageHeaderTokens = defaultODSPageHeaderTokens
