package com.telekom.odsystem.organisms.cardproduct

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSCorners
import com.telekom.odsystem.foundations.ODSPadding
import com.telekom.odsystem.foundations.SCALE_FACTOR

/**
 * Code generated with ODS RADD Code Generator Plugin
 * 2025-06-19 (v1.31.6) - uid: 38f7406a
 * Figma link: https://figma.com/design/RTdgj2EBwu8TwoaWWVEovL/ODS_OneID_Production_Library?node-id=15585-710
 */

data class ODSCardProductTokens(
    val gap: Dp,
    val widthSizeSmallV: Dp, // Not used in mobile
    val width: Dp, // Not used in mobile
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignment: Alignment.Horizontal,
    val verticalArrangementSizeSmallV: Arrangement.Vertical,
    val verticalArrangementSizeMedium: Arrangement.Vertical,
    val verticalArrangementSizeLarge: Arrangement.Vertical,
    val horizontalArrangementSizeSmallH: Arrangement.Horizontal,
    val cardZStackContentAlignment: Alignment,
    val cardGapSizeSmallV: Dp,
    val cardGapSizeSmallH: Dp,
    val cardGapSizeMedium: Dp,
    val cardGapSizeLarge: Dp,
    val cardPaddingSizeSmallV: ODSPadding,
    val cardPaddingSizeSmallH: ODSPadding,
    val cardPaddingSizeMedium: ODSPadding,
    val cardPaddingSizeLarge: ODSPadding,
    val cardVerticalAlignment: Alignment.Vertical,
    val cardHorizontalAlignment: Alignment.Horizontal,
    val cardVerticalArrangement: Arrangement.Vertical,
    val cardContentAlignment: Alignment,
    val cardBgCornerRadiusSizeSmallV: ODSCorners,
    val cardBgCornerRadiusSizeSmallH: ODSCorners,
    val cardBgCornerRadiusSizeMedium: ODSCorners,
    val cardBgCornerRadiusSizeLarge: ODSCorners,
    val tagContainerVerticalAlignment: Alignment.Vertical,
    val tagContainerHorizontalAlignment: Alignment.Horizontal,
    val tagContainerVerticalArrangement: Arrangement.Vertical,
    val tagContainerPaddingSizeLarge: ODSPadding,
    val imageContainerHeightSizeSmallV: Dp,
    val imageContainerHeightSizeSmallH: Dp,
    val imageContainerHeightSizeMedium: Dp,
    val imageContainerHeightSizeLarge: Dp,
    val imageContainerVerticalAlignment: Alignment.Vertical,
    val imageContainerHorizontalAlignment: Alignment.Horizontal,
    val imageContainerHorizontalArrangement: Arrangement.Horizontal,
    val colourSwatchContainerPaddingSizeSmallV: ODSPadding,
    val colourSwatchContainerPaddingSizeSmallH: ODSPadding,
    val colourSwatchContainerPaddingSizeMedium: ODSPadding,
    val colourSwatchContainerPaddingSizeLarge: ODSPadding,
    val colourSwatchContainerMinHeightSizeSmallV: Dp,
    val colourSwatchContainerMinHeightSizeSmallH: Dp,
    val colourSwatchContainerMinHeightSizeMedium: Dp,
    val colourSwatchContainerMinHeightSizeLarge: Dp,
    val colourSwatchContainerVerticalAlignment: Alignment.Vertical,
    val colourSwatchContainerHorizontalAlignment: Alignment.Horizontal,
    val colourSwatchContainerVerticalArrangement: Arrangement.Vertical,
    val descriptionGap: Dp,
    val descriptionVerticalAlignment: Alignment.Vertical,
    val descriptionHorizontalAlignment: Alignment.Horizontal,
    val descriptionVerticalArrangement: Arrangement.Vertical,
    val descriptionPaddingSizeSmallH: ODSPadding,
    val contentSlotContainerVerticalAlignment: Alignment.Vertical,
    val contentSlotContainerHorizontalAlignment: Alignment.Horizontal,
    val contentSlotContainerVerticalArrangement: Arrangement.Vertical,
    val featuresSlotContainerVerticalAlignment: Alignment.Vertical,
    val featuresSlotContainerHorizontalAlignment: Alignment.Horizontal,
    val featuresSlotContainerVerticalArrangement: Arrangement.Vertical,
    val priceSlotContainerVerticalAlignment: Alignment.Vertical,
    val priceSlotContainerHorizontalAlignment: Alignment.Horizontal,
    val priceSlotContainerVerticalArrangement: Arrangement.Vertical,
    val actionSlotContainerVerticalAlignment: Alignment.Vertical,
    val actionSlotContainerHorizontalAlignment: Alignment.Horizontal,
    val actionSlotContainerHorizontalArrangement: Arrangement.Horizontal,
    val scaleFactor: Float, // Not exported by plugin
)

val defaultODSCardProductTokens = ODSCardProductTokens(
    gap = DSVariables.spacingComponent5,
    widthSizeSmallV = DSVariables.columns3Columns,
    width = DSVariables.columns6Columns,
    verticalAlignment = Alignment.Top,
    horizontalAlignment = Alignment.Start,
    verticalArrangementSizeSmallV = Arrangement.Top,
    verticalArrangementSizeMedium = Arrangement.Top,
    verticalArrangementSizeLarge = Arrangement.Top,
    horizontalArrangementSizeSmallH = Arrangement.Start,
    cardZStackContentAlignment = Alignment.TopCenter,
    cardGapSizeSmallV = DSVariables.spacingComponent3,
    cardGapSizeSmallH = DSVariables.spacingComponent3,
    cardGapSizeMedium = DSVariables.spacingComponent4,
    cardGapSizeLarge = DSVariables.spacingComponent5,
    cardPaddingSizeSmallV = ODSPadding(all = DSVariables.spacingComponent5),
    cardPaddingSizeSmallH = ODSPadding(all = DSVariables.spacingComponent5),
    cardPaddingSizeMedium = ODSPadding(all = DSVariables.spacingComponent7),
    cardPaddingSizeLarge = ODSPadding(all = DSVariables.spacingComponent8),
    cardVerticalAlignment = Alignment.Top,
    cardHorizontalAlignment = Alignment.CenterHorizontally,
    cardVerticalArrangement = Arrangement.Top,
    cardContentAlignment = Alignment.TopCenter,
    cardBgCornerRadiusSizeSmallV = ODSCorners(all = DSVariables.radiusMedium),
    cardBgCornerRadiusSizeSmallH = ODSCorners(all = DSVariables.radiusMedium),
    cardBgCornerRadiusSizeMedium = ODSCorners(all = DSVariables.radiusLarge),
    cardBgCornerRadiusSizeLarge = ODSCorners(all = DSVariables.radiusLarge),
    tagContainerVerticalAlignment = Alignment.Top,
    tagContainerHorizontalAlignment = Alignment.Start,
    tagContainerVerticalArrangement = Arrangement.Top,
    tagContainerPaddingSizeLarge = ODSPadding(bottom = DSVariables.spacingComponent2),
    imageContainerHeightSizeSmallV = 160.dp,
    imageContainerHeightSizeSmallH = 160.dp,
    imageContainerHeightSizeMedium = 200.dp,
    imageContainerHeightSizeLarge = 256.dp,
    imageContainerVerticalAlignment = Alignment.CenterVertically,
    imageContainerHorizontalAlignment = Alignment.CenterHorizontally,
    imageContainerHorizontalArrangement = Arrangement.Center,
    colourSwatchContainerPaddingSizeSmallV = ODSPadding(top = DSVariables.spacingComponent4),
    colourSwatchContainerPaddingSizeSmallH = ODSPadding(top = DSVariables.spacingComponent4),
    colourSwatchContainerPaddingSizeMedium = ODSPadding(top = DSVariables.spacingComponent4),
    colourSwatchContainerPaddingSizeLarge = ODSPadding(top = DSVariables.spacingComponent5),
    colourSwatchContainerMinHeightSizeSmallV = DSVariables.sizingComponent11,
    colourSwatchContainerMinHeightSizeSmallH = DSVariables.sizingComponent11,
    colourSwatchContainerMinHeightSizeMedium = DSVariables.sizingComponent11,
    colourSwatchContainerMinHeightSizeLarge = DSVariables.sizingComponent12,
    colourSwatchContainerVerticalAlignment = Alignment.Top,
    colourSwatchContainerHorizontalAlignment = Alignment.Start,
    colourSwatchContainerVerticalArrangement = Arrangement.Top,
    descriptionGap = DSVariables.spacingComponent7,
    descriptionVerticalAlignment = Alignment.Top,
    descriptionHorizontalAlignment = Alignment.CenterHorizontally,
    descriptionVerticalArrangement = Arrangement.Top,
    descriptionPaddingSizeSmallH = ODSPadding(top = DSVariables.spacingComponent3),
    contentSlotContainerVerticalAlignment = Alignment.Top,
    contentSlotContainerHorizontalAlignment = Alignment.Start,
    contentSlotContainerVerticalArrangement = Arrangement.Top,
    featuresSlotContainerVerticalAlignment = Alignment.Top,
    featuresSlotContainerHorizontalAlignment = Alignment.Start,
    featuresSlotContainerVerticalArrangement = Arrangement.Top,
    priceSlotContainerVerticalAlignment = Alignment.Top,
    priceSlotContainerHorizontalAlignment = Alignment.Start,
    priceSlotContainerVerticalArrangement = Arrangement.Top,
    actionSlotContainerVerticalAlignment = Alignment.Top,
    actionSlotContainerHorizontalAlignment = Alignment.Start,
    actionSlotContainerHorizontalArrangement = Arrangement.Start,
    scaleFactor = SCALE_FACTOR
)

var DSCardProductTokens: ODSCardProductTokens = defaultODSCardProductTokens
