package com.telekom.odsystem.slots.productcardprice

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.ui.Alignment
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import com.telekom.odsystem.DSTextStyles
import com.telekom.odsystem.DSVariables
import com.telekom.odsystem.foundations.ODSTextStyle

data class ODSProductCardPriceTokens(
    val gapFinancialOptionsOneTimeOnly: Dp,
    val gapFinancialOptionsInstallmentsOnly: Dp,
    val gapFinancialOptionsOneTimeOrInstallments: Dp,
    val verticalAlignment: Alignment.Vertical,
    val horizontalAlignment: Alignment.Horizontal,
    val verticalArrangement: Arrangement.Vertical,
    val priceContainerGap: Dp,
    val priceContainerVerticalAlignment: Alignment.Vertical,
    val priceContainerHorizontalAlignment: Alignment.Horizontal,
    val priceContainerVerticalArrangement: Arrangement.Vertical,
    val labelStyle: ODSTextStyle,
    val labelTextAlign: TextAlign,
    val priceStyle: ODSTextStyle,
    val priceTextAlign: TextAlign,
    val priceSavingsGap: Dp,
    val priceSavingsVerticalAlignment: Alignment.Vertical,
    val priceSavingsHorizontalAlignment: Alignment.Horizontal,
    val priceSavingsHorizontalArrangement: Arrangement.Horizontal,
    val beforePriceStrikeThroughZStackContentAlignment: Alignment,
    val beforePriceStrikeThroughVerticalAlignment: Alignment.Vertical,
    val beforePriceStrikeThroughHorizontalAlignment: Alignment.Horizontal,
    val beforePriceStrikeThroughVerticalArrangement: Arrangement.Vertical,
    val beforePriceStrikeThroughContentAlignment: Alignment,
    val priceBeforeStyle: ODSTextStyle,
    val priceBeforeTextAlign: TextAlign,
    val strikeThroughAbsoluteContentAlignment: Alignment,
    val strikeThroughHeight: Dp,
    val installmentsContainerGap: Dp,
    val installmentsContainerVerticalAlignment: Alignment.Vertical,
    val installmentsContainerHorizontalAlignment: Alignment.Horizontal,
    val installmentsContainerVerticalArrangement: Arrangement.Vertical,
    val installmentsSavingsGap: Dp,
    val installmentsSavingsVerticalAlignment: Alignment.Vertical,
    val installmentsSavingsHorizontalAlignment: Alignment.Horizontal,
    val installmentsSavingsHorizontalArrangement: Arrangement.Horizontal,
    val beforePriceStrikeThrough2ZStackContentAlignment: Alignment,
    val beforePriceStrikeThrough2VerticalAlignment: Alignment.Vertical,
    val beforePriceStrikeThrough2HorizontalAlignment: Alignment.Horizontal,
    val beforePriceStrikeThrough2VerticalArrangement: Arrangement.Vertical,
    val beforePriceStrikeThrough2ContentAlignment: Alignment,
    val priceBefore2Style: ODSTextStyle,
    val priceBefore2TextAlign: TextAlign,
    val strikeThrough2AbsoluteContentAlignment: Alignment,
    val strikeThrough2Height: Dp,
    val installmentsTextStyle: ODSTextStyle,
    val installmentsTextTextAlign: TextAlign,
    val installmentStyle: ODSTextStyle,
    val installmentTextAlign: TextAlign,
    val supportTextStyle: ODSTextStyle,
    val supportTextTextAlign: TextAlign
)

val defaultODSProductCardPriceTokens = ODSProductCardPriceTokens(
    gapFinancialOptionsOneTimeOnly = DSVariables.spacingComponent3,
    gapFinancialOptionsInstallmentsOnly = DSVariables.spacingComponent3,
    gapFinancialOptionsOneTimeOrInstallments = DSVariables.spacingComponent5,
    verticalAlignment = Alignment.CenterVertically,
    horizontalAlignment = Alignment.Start,
    verticalArrangement = Arrangement.Center,
    priceContainerGap = DSVariables.spacingComponent2,
    priceContainerVerticalAlignment = Alignment.Top,
    priceContainerHorizontalAlignment = Alignment.Start,
    priceContainerVerticalArrangement = Arrangement.Top,
    labelStyle = DSTextStyles.bodyMBold,
    labelTextAlign = TextAlign.Left,
    priceStyle = DSTextStyles.subtitle,
    priceTextAlign = TextAlign.Left,
    priceSavingsGap = DSVariables.spacingComponent3,
    priceSavingsVerticalAlignment = Alignment.CenterVertically,
    priceSavingsHorizontalAlignment = Alignment.Start,
    priceSavingsHorizontalArrangement = Arrangement.Start,
    beforePriceStrikeThroughZStackContentAlignment = Alignment.TopStart,
    beforePriceStrikeThroughVerticalAlignment = Alignment.Top,
    beforePriceStrikeThroughHorizontalAlignment = Alignment.Start,
    beforePriceStrikeThroughVerticalArrangement = Arrangement.Top,
    beforePriceStrikeThroughContentAlignment = Alignment.TopStart,
    priceBeforeStyle = DSTextStyles.bodyMBold,
    priceBeforeTextAlign = TextAlign.Left,
    strikeThroughAbsoluteContentAlignment = Alignment.CenterStart,
    strikeThroughHeight = 2.dp,
    installmentsContainerGap = DSVariables.spacingComponent2,
    installmentsContainerVerticalAlignment = Alignment.Top,
    installmentsContainerHorizontalAlignment = Alignment.Start,
    installmentsContainerVerticalArrangement = Arrangement.Top,
    installmentsSavingsGap = DSVariables.spacingComponent3,
    installmentsSavingsVerticalAlignment = Alignment.CenterVertically,
    installmentsSavingsHorizontalAlignment = Alignment.Start,
    installmentsSavingsHorizontalArrangement = Arrangement.Start,
    beforePriceStrikeThrough2ZStackContentAlignment = Alignment.TopStart,
    beforePriceStrikeThrough2VerticalAlignment = Alignment.Top,
    beforePriceStrikeThrough2HorizontalAlignment = Alignment.Start,
    beforePriceStrikeThrough2VerticalArrangement = Arrangement.Top,
    beforePriceStrikeThrough2ContentAlignment = Alignment.TopStart,
    priceBefore2Style = DSTextStyles.bodyMBold,
    priceBefore2TextAlign = TextAlign.Left,
    strikeThrough2AbsoluteContentAlignment = Alignment.CenterStart,
    strikeThrough2Height = 2.dp,
    installmentsTextStyle = DSTextStyles.bodyMBold,
    installmentsTextTextAlign = TextAlign.Left,
    installmentStyle = DSTextStyles.subtitle,
    installmentTextAlign = TextAlign.Left,
    supportTextStyle = DSTextStyles.microcopyRegular,
    supportTextTextAlign = TextAlign.Left
)

var DSProductCardPriceTokens: ODSProductCardPriceTokens = defaultODSProductCardPriceTokens
